import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import type { ViewProps } from 'react-native';
import { a11yProps } from '../../core/accessibility/a11yProps';
import { useA11yId } from '../../core/accessibility/useA11yId';
import { factory } from '../../core/factory';
import { webProps } from '../../core/platform';
import { useFloating } from '../../core/overlay/useFloating';
import { useTheme } from '../../core/theme/ThemeProvider';
import { useDirection } from '../../core/providers/DirectionProvider';
import { useStyleProps } from '../../core/utils/spacing';
import { useControllableState } from '../../hooks/useControllableState';
import { useOverlayMode } from '../../hooks/useOverlayMode';
import { DropdownSheet } from '../_internal/DropdownSheet/DropdownSheet';
import { Field } from '../_internal/Field/Field';
import { Icon } from '../Icon';
import { PickerTrigger } from '../Select/PickerTrigger';
import { getDropdownSurfaceStyle } from '../Select/fieldControlStyles';
import { CascaderColumns } from './CascaderColumns';
import { columnsForPath, findPath, flattenPaths } from './cascaderUtils';
import { isInSafeArea } from './safeAreaPolygon';
import type { CascaderOption, CascaderProps } from './types';
const Root = factory<{ props: CascaderProps; ref: View }>((props, ref) => {
  const { data, value: valueProp, defaultValue, onChange, placeholder = 'Select…', changeOnSelect = false, allowDeselect = true, closeOnSelect = !allowDeselect, expandTrigger = 'click', safeAreaPolygon = true, withColumns = true, maxDisplayedLevels = 3, previousLevelsControlLabel = 'Previous levels', nextLevelsControlLabel = 'Next levels', searchable = false, filter, renderSearchOption, searchValue, defaultSearchValue, onSearchChange, nothingFoundMessage = 'Nothing found', openOnFocus = false, separator = ' / ', formatValue, columnWidth = 180, maxDropdownHeight = 260, renderOption, withCheckIcon = true, checkIconPosition = 'end', clearable = false, dropdownOpened, defaultDropdownOpened, onDropdownOpen, onDropdownClose, position = 'bottom-start', offset = 6, dropdownWidth = 'target', label, description, error, helperText, required, withAsterisk, disabled, readOnly, size = 'md', radius, variant, accessibilityLabel, accessibilityHint, startSection, style, testID } = props;
  const theme = useTheme(); const { isRTL } = useDirection(); const hoverTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const pointer = useRef({ x: 0, y: 0 }); const origins = useRef<Record<number, { x: number; y: number }>>({}); const spacing = useStyleProps(props); const { shouldUseModal } = useOverlayMode(); const anchor = useRef<View>(null);
  const id = useA11yId(undefined, 'plocks-cascader');
  const listId = `${id}-list`;
  const [value, setValue] = useControllableState<string[] | null>({ value: valueProp, defaultValue, finalValue: null });
  const [opened, setOpened] = useControllableState({ value: dropdownOpened, defaultValue: defaultDropdownOpened, finalValue: false, onChange: (next) => next ? onDropdownOpen?.() : onDropdownClose?.() });
  const [query, setQuery] = useControllableState({ value: searchValue, defaultValue: defaultSearchValue, finalValue: '', onChange: onSearchChange });
  const [path, setPath] = useState<string[]>(value ?? []); const [active, setActive] = useState({ level: 0, index: 0 }); const [columnStart, setColumnStart] = useState(0);
  useEffect(() => { if (valueProp !== undefined) setPath(valueProp ?? []); }, [valueProp]);
  useEffect(() => () => { if (hoverTimer.current) clearTimeout(hoverTimer.current); }, []);
  const resolved = useMemo(() => findPath(data, value ?? []), [data, value]);
  const display = formatValue ? formatValue(resolved) : resolved.map((item) => item.label ?? item.value).join(separator);
  const columns = useMemo(() => columnsForPath(data, path), [data, path]);
  useEffect(() => {
    if (!opened || expandTrigger !== 'hover' || !withColumns || shouldUseModal || typeof document === 'undefined') return;
    const track = (event: MouseEvent) => {
      pointer.current = { x: event.clientX, y: event.clientY };
      path.forEach((selected, level) => {
        const index = columns[level]?.findIndex((option) => option.value === selected) ?? -1;
        const row = index < 0 ? null : document.getElementById(`${id}-option-${level}-${index}`);
        const rect = row?.getBoundingClientRect();
        if (rect && event.clientX >= rect.left && event.clientX <= rect.right && event.clientY >= rect.top && event.clientY <= rect.bottom) origins.current[level] = pointer.current;
      });
    };
    document.addEventListener('mousemove', track);
    return () => document.removeEventListener('mousemove', track);
  }, [opened, expandTrigger, withColumns, shouldUseModal, path, columns, id]);
  const flat = useMemo(() => flattenPaths(data).filter((chain) => !chain.some((item) => item.disabled) && (filter ? filter(query, chain) : chain.some((item) => (item.label ?? item.value).toLowerCase().includes(query.toLowerCase())))), [data, filter, query]);
  const close = () => { if (hoverTimer.current) clearTimeout(hoverTimer.current); setOpened(false); setQuery(''); };
  const choose = (chain: CascaderOption[]) => { const next = chain.map((item) => item.value); if (allowDeselect && value?.join('/') === next.join('/')) { setValue(null); onChange?.(null, []); } else { setValue(next); onChange?.(next, chain); } if (closeOnSelect) close(); };
  const press = (level: number, index: number) => { const option = columns[level]?.[index]; if (!option || option.disabled) return; const next = [...path.slice(0, level), option.value]; const chain = findPath(data, next); setPath(next); setActive(option.children?.length ? { level: level + 1, index: Math.max(0, option.children.findIndex((child) => !child.disabled)) } : { level, index }); if (option.children?.length) { if (changeOnSelect) choose(chain); } else choose(chain); if (level + 1 >= columnStart + maxDisplayedLevels) setColumnStart(Math.max(0, level + 2 - maxDisplayedLevels)); };
  const hover = (level: number, index: number) => {
    setActive({ level, index });
    if (hoverTimer.current) clearTimeout(hoverTimer.current);
    const option = columns[level]?.[index];
    if (expandTrigger !== 'hover' || !option?.children?.length || path[level] === option.value) return;
    const next = [...path.slice(0, level), option.value];
    const origin = origins.current[level];
    const childColumn = typeof document === 'undefined' ? null : document.getElementById(`${id}-column-${level + 1}`);
    const buffer = typeof safeAreaPolygon === 'object' ? safeAreaPolygon.buffer ?? 5 : 5;
    const inCorridor = safeAreaPolygon !== false && origin && childColumn && isInSafeArea(pointer.current, origin, childColumn.getBoundingClientRect(), isRTL, buffer);
    if (inCorridor) hoverTimer.current = setTimeout(() => { origins.current[level] = pointer.current; setPath(next); }, 300);
    else { origins.current[level] = pointer.current; setPath(next); }
  };
  const onKeyDown = (event: { key?: string; nativeEvent?: unknown; preventDefault(): void }) => { if (disabled || readOnly) return; const key = event.key ?? (event.nativeEvent as { key?: string } | undefined)?.key; if (!opened && (key === 'ArrowDown' || key === 'Enter' || key === ' ')) { event.preventDefault(); setOpened(true); setActive({ level: 0, index: Math.max(0, data.findIndex((item) => !item.disabled)) }); return; } if (!opened) return; const items = columns[active.level] ?? data; const enabled = (index: number) => index >= 0 && index < items.length && !items[index].disabled; if (key === 'ArrowDown' || key === 'ArrowUp') { event.preventDefault(); const step = key === 'ArrowDown' ? 1 : -1; let next = active.index + step; while (next >= 0 && next < items.length && !enabled(next)) next += step; if (enabled(next)) setActive({ level: active.level, index: next }); } else if (key === 'Home' || key === 'End') { event.preventDefault(); const fromEnd = [...items].reverse().findIndex((item) => !item.disabled); const next = key === 'Home' ? items.findIndex((item) => !item.disabled) : fromEnd < 0 ? -1 : items.length - 1 - fromEnd; if (next >= 0) setActive({ level: active.level, index: next }); } else if (key === (isRTL ? 'ArrowLeft' : 'ArrowRight') || key === 'Enter') { event.preventDefault(); if (enabled(active.index)) press(active.level, active.index); } else if (key === (isRTL ? 'ArrowRight' : 'ArrowLeft')) { event.preventDefault(); setActive({ level: Math.max(0, active.level - 1), index: 0 }); setPath(path.slice(0, -1)); } else if (key === 'Escape') { event.preventDefault(); close(); } };
  const search = searchable && <TextInput value={query} onChangeText={setQuery} onKeyPress={onKeyDown} placeholder="Search…" aria-label="Search" style={{ padding: 10, color: theme.text.primary }} />;
  const flatList = <ScrollView style={{ maxHeight: maxDropdownHeight }}><View {...a11yProps({ role: 'listbox', label: 'Paths', id: listId })}>{flat.map((chain) => <Pressable key={chain.map((item) => item.value).join('/')} onPress={() => choose(chain)} {...a11yProps({ role: 'option', selected: value?.join('/') === chain.map((item) => item.value).join('/') })} style={{ padding: 10 }}><Text style={{ color: theme.text.primary }}>{renderSearchOption?.(chain) ?? chain.map((item) => item.label ?? item.value).join(separator)}</Text></Pressable>)}{flat.length === 0 && <Text style={{ padding: 10, color: theme.text.muted }}>{nothingFoundMessage}</Text>}</View></ScrollView>;
  const start = Math.max(0, Math.min(columnStart, columns.length - maxDisplayedLevels));
  const columnList = <View {...a11yProps({ id: listId })}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>{start > 0 && <Pressable onPress={() => setColumnStart(start - 1)} accessibilityLabel={previousLevelsControlLabel}><Text>{previousLevelsControlLabel}</Text></Pressable>}{start + maxDisplayedLevels < columns.length && <Pressable onPress={() => setColumnStart(start + 1)} accessibilityLabel={nextLevelsControlLabel}><Text>{nextLevelsControlLabel}</Text></Pressable>}</View><CascaderColumns columns={columns.slice(start, start + maxDisplayedLevels)} path={path} value={value} active={active} onHover={hover} onPress={press} columnWidth={columnWidth} maxHeight={maxDropdownHeight} renderOption={renderOption} withCheckIcon={withCheckIcon} checkIconPosition={checkIconPosition} idPrefix={id} start={start} /></View>;
  const showingColumns = withColumns && !shouldUseModal && !query;
  const list = showingColumns ? columnList : flatList;
  const activeId = showingColumns && opened && columns[active.level]?.[active.index] && !columns[active.level][active.index].disabled ? `${id}-option-${active.level}-${active.index}` : undefined;
  const floating = useFloating({ opened: opened && !shouldUseModal, onDismiss: close, placement: position, offset, matchWidth: dropdownWidth === 'target', role: null, popupType: 'listbox', layer: 'dropdown', autoFocus: searchable });
  const content = <View {...floating.getFloatingProps({ style: [getDropdownSurfaceStyle(theme), typeof dropdownWidth === 'number' ? { width: dropdownWidth } : null] }) as ViewProps}>{search}{list}</View>;
  const setAnchor = (node: View | null) => { anchor.current = node; floating.refs.setReference(node); };
  return <Field id={id} label={label} description={description} error={error} helperText={helperText} required={required} withAsterisk={withAsterisk} disabled={disabled} readOnly={readOnly} size={size} accessibilityLabel={accessibilityLabel} accessibilityHint={accessibilityHint} style={[spacing, style]} testID={testID}>{({ controlProps, invalid }) => <View ref={ref}><PickerTrigger triggerRef={setAnchor} triggerProps={{ ...controlProps, ...a11yProps({ role: 'combobox', expanded: opened, hasPopup: 'listbox', controls: listId, activeDescendant: activeId }), ...webProps({ onKeyDown }), onFocus: openOnFocus && !readOnly && !disabled ? () => setOpened(true) : undefined }} onPress={() => { if (!disabled && !readOnly) setOpened(!opened); }} displayValue={display} placeholder={placeholder} size={size} radius={radius} variant={variant} invalid={invalid} opened={opened} disabled={disabled} readOnly={readOnly} startSection={startSection} endSection={<Icon name="chevron-down" decorative />} showClear={clearable && !!value} onClear={() => { setValue(null); onChange?.(null, []); }} />{!shouldUseModal && floating.renderFloating(content)}{shouldUseModal && <DropdownSheet opened={opened} onClose={close} title={label ?? placeholder} accessibilityLabel={accessibilityLabel ?? placeholder} placement="center" withCloseButton>{search}{flatList}</DropdownSheet>}</View>}</Field>;
}, { displayName: 'Cascader' });
export const Cascader = Root;
