import React from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { a11yProps } from '../../core/accessibility/a11yProps';
import { webProps } from '../../core/platform';
import { useTheme } from '../../core/theme/ThemeProvider';
import { Icon } from '../Icon';
import type { CascaderOption } from './types';
export function CascaderColumns({ columns, path, value, active, onHover, onPress, columnWidth, maxHeight, renderOption, withCheckIcon, checkIconPosition, idPrefix, start = 0 }: { columns: CascaderOption[][]; path: string[]; value: string[] | null; active: { level: number; index: number }; onHover: (level: number, index: number) => void; onPress: (level: number, index: number) => void; columnWidth: number; maxHeight: number; renderOption?: (option: CascaderOption, level: number) => React.ReactNode; withCheckIcon: boolean; checkIconPosition: 'start' | 'end'; idPrefix: string; start?: number }) {
  const theme = useTheme();
  return <View style={{ flexDirection: 'row' }}>{columns.map((items, level) => <ScrollView key={level + start} style={{ width: columnWidth, maxHeight, borderStartWidth: level ? 1 : 0, borderColor: theme.backgrounds.border }}><View {...a11yProps({ role: 'listbox', label: `Level ${level + start + 1}`, id: `${idPrefix}-column-${level + start}` })}>{items.map((option, index) => { const selected = value?.[level + start] === option.value && value.length === level + start + 1; const inPath = path[level + start] === option.value; return <Pressable key={option.value} {...a11yProps({ role: 'option', selected, disabled: !!option.disabled, id: `${idPrefix}-option-${level + start}-${index}` })} disabled={option.disabled} onPress={() => onPress(level + start, index)} onHoverIn={() => onHover(level + start, index)} {...webProps({ tabIndex: -1 })} style={{ padding: 10, minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: active.level === level + start && active.index === index ? theme.backgrounds.hover : inPath ? theme.backgrounds.subtle : undefined, opacity: option.disabled ? 0.5 : 1 }}>{withCheckIcon && checkIconPosition === 'start' && selected ? <Icon name="check" size="sm" decorative /> : null}<Text style={{ flex: 1, color: theme.text.primary }}>{renderOption?.(option, level + start) ?? option.label ?? option.value}</Text>{option.children?.length ? <Icon name="chevron-right" size="sm" decorative /> : null}{withCheckIcon && checkIconPosition === 'end' && selected ? <Icon name="check" size="sm" decorative /> : null}</Pressable>; })}</View></ScrollView>)}</View>;
}
