import type { BrandName } from '@platform-blocks/ui';

export const FEATURED_BRANDS: BrandName[] = [
  'google',
  'facebook',
  'apple',
  'github',
  'x',
  'microsoft',
  'linkedin',
  'discord',
  'slack',
  'chrome',
  'openai',
  'spotify',
  'youtube'
];

export const ALL_BRANDS: BrandName[] = [
  'google',
  'google-play',
  'facebook',
  'discord',
  'android',
  'apple',
  'apple-podcasts',
  'app-store',
  'app-gallery',
  'galaxy-store',
  'anthropic',
  'openai',
  'chrome',
  'spotify',
  'github',
  'x',
  'microsoft',
  'linkedin',
  'slack',
  'youtube',
  'youtube-music',
  'mastercard',
  'visa',
  'threads',
  'bluesky',
  'pinterest',
  'snapchat',
  'wechat',
  'reddit',
  'amazon',
  'amazon-music',
  'twitch',
  'tiktok',
  'expo',
  'react',
  'nodejs',
  'npm',
  'typescript',
  'css',
  'stripe',
  'apple-pay',
  'google-pay',
  'paypal',
  'apple-music',
  'soundcloud',
  'whatsapp',
  'telegram',
  'signal',
  'meta',
  'discover',
  'amex',
  'messenger',
  'instagram',
  'zoom',
];

export const SAMPLE_BRANDS: BrandName[] = FEATURED_BRANDS.slice(0, 6);

export const DARK_MODE_BRANDS: BrandName[] = ['apple', 'github', 'x'];
