import React from 'react';
import { act, fireEvent, render, screen } from '@testing-library/react';
import { PlocksProvider } from '../../../core/theme/PlocksProvider';
import { TreeSelect } from '../TreeSelect';
const originalRect = Element.prototype.getBoundingClientRect;
beforeAll(() => { Element.prototype.getBoundingClientRect = () => ({ x: 20, y: 40, top: 40, left: 20, right: 220, bottom: 80, width: 200, height: 40, toJSON: () => ({}) }) as DOMRect; });
afterAll(() => { Element.prototype.getBoundingClientRect = originalRect; });
it('selects a leaf from the tree', async () => {
  render(<PlocksProvider><TreeSelect label="Food" data={[{ id: 'fruit', label: 'Fruit', children: [{ id: 'apple', label: 'Apple' }] }]} /></PlocksProvider>);
  fireEvent.click(screen.getByRole('combobox', { name: 'Food' }));
  await act(async () => { await new Promise((resolve) => setTimeout(resolve, 150)); });
  fireEvent.click(screen.getByText('Fruit'));
  fireEvent.click(screen.getByText('Apple'));
  expect(screen.getByRole('combobox', { name: 'Food' }).textContent).toContain('Apple');
});
it('opens by keyboard, exposes its controlled popup, and selects through tree keys', async () => {
  const onChange = jest.fn();
  render(<PlocksProvider><TreeSelect label="Food" data={[{ id: 'apple', label: 'Apple' }, { id: 'pear', label: 'Pear' }]} onChange={onChange} /></PlocksProvider>);
  const trigger = screen.getByRole('combobox', { name: 'Food' });
  fireEvent.keyDown(trigger, { key: 'ArrowDown' });
  await act(async () => { await new Promise((resolve) => setTimeout(resolve, 150)); });
  expect(trigger.getAttribute('aria-expanded')).toBe('true');
  expect(document.getElementById(trigger.getAttribute('aria-controls')!)?.contains(screen.getByRole('tree'))).toBe(true);
  const tree = screen.getByRole('tree');
  act(() => tree.focus());
  fireEvent.keyDown(tree, { key: 'ArrowDown' });
  fireEvent.keyDown(tree, { key: 'Enter' });
  expect(onChange).toHaveBeenCalledWith('pear');
  expect(trigger.textContent).toContain('Pear');
});
it('preserves a controlled value and ignores opening keys when read only', async () => {
  const onChange = jest.fn();
  const data = [{ id: 'apple', label: 'Apple' }, { id: 'pear', label: 'Pear' }];
  const view = render(<PlocksProvider><TreeSelect label="Food" data={data} value="apple" onChange={onChange} /></PlocksProvider>);
  fireEvent.click(screen.getByRole('combobox', { name: 'Food' }));
  await act(async () => { await new Promise((resolve) => setTimeout(resolve, 150)); });
  fireEvent.click(screen.getByRole('treeitem', { name: 'Pear' }));
  expect(onChange).toHaveBeenCalledWith('pear');
  expect(screen.getByRole('combobox', { name: 'Food' }).textContent).toContain('Apple');
  view.rerender(<PlocksProvider><TreeSelect label="Food" data={data} value="pear" onChange={onChange} readOnly /></PlocksProvider>);
  const trigger = screen.getByRole('combobox', { name: 'Food' });
  expect(trigger.textContent).toContain('Pear');
  fireEvent.keyDown(trigger, { key: 'ArrowDown' });
  expect(trigger.getAttribute('aria-expanded')).toBe('false');
});
it('applies checkbox selection to leaves and lets a pill remove one', async () => {
  const onChange = jest.fn();
  render(<PlocksProvider><TreeSelect label="Food" mode="checkbox" data={[{ id: 'fruit', label: 'Fruit', children: [{ id: 'apple', label: 'Apple' }, { id: 'pear', label: 'Pear' }] }]} defaultValue={['apple']} defaultExpandedValues={['fruit']} onChange={onChange} /></PlocksProvider>);
  fireEvent.click(screen.getByRole('combobox', { name: 'Food' }));
  await act(async () => { await new Promise((resolve) => setTimeout(resolve, 150)); });
  const tree = screen.getByRole('tree');
  act(() => tree.focus());
  fireEvent.keyDown(tree, { key: 'ArrowRight' });
  fireEvent.keyDown(tree, { key: 'ArrowDown' });
  fireEvent.keyDown(tree, { key: ' ' });
  expect(onChange).toHaveBeenLastCalledWith(['apple', 'pear']);
  fireEvent.click(screen.getByRole('button', { name: 'Remove Apple' }));
  expect(onChange).toHaveBeenLastCalledWith(['pear']);
});
