export const NODES = [
  { id: 'campus', name: 'Campus Recruiting' },
  { id: 'bootcamp', name: 'Bootcamp Partners' },
  { id: 'referrals', name: 'Employee Referrals' },
  { id: 'internal', name: 'Internal Mobility' },
  { id: 'screening', name: 'Recruiter Screen' },
  { id: 'technical', name: 'Technical Interview' },
  { id: 'onsite', name: 'Onsite Panel' },
  { id: 'offer', name: 'Offer Stage' },
  { id: 'accepted', name: 'Accepted Offers', color: '#10B981' },
  { id: 'screening-drop', name: 'Screen Drops', color: '#EF4444' },
  { id: 'technical-drop', name: 'Technical Drops', color: '#DC2626' },
  { id: 'onsite-drop', name: 'Onsite Declines', color: '#B91C1C' },
  { id: 'offer-decline', name: 'Offer Declined', color: '#F43F5E' },
  { id: 'product-eng', name: 'Product Engineering' },
  { id: 'platform-eng', name: 'Platform Engineering' },
  { id: 'data-science', name: 'Data Science' },
];

export const LINKS = [
  { source: 'campus', target: 'screening', value: 120 },
  { source: 'bootcamp', target: 'screening', value: 80 },
  { source: 'referrals', target: 'technical', value: 60 },
  { source: 'internal', target: 'technical', value: 30 },
  { source: 'screening', target: 'technical', value: 190 },
  { source: 'screening', target: 'screening-drop', value: 10 },
  { source: 'technical', target: 'onsite', value: 210 },
  { source: 'technical', target: 'technical-drop', value: 70 },
  { source: 'onsite', target: 'offer', value: 180 },
  { source: 'onsite', target: 'onsite-drop', value: 30 },
  { source: 'offer', target: 'accepted', value: 140 },
  { source: 'offer', target: 'offer-decline', value: 40 },
  { source: 'accepted', target: 'product-eng', value: 60 },
  { source: 'accepted', target: 'platform-eng', value: 45 },
  { source: 'accepted', target: 'data-science', value: 35 },
];
