// Auto-generated source code map for demo components
// This file is generated by scripts/generate-source-map.ts
// Do not edit this file manually - run 'npm run generate:source-map' instead

export const sourceCodeMap: Record<string, string> = {
};

/**
 * Get source code for a demo component
 */
export function getSourceCode(componentName: string, demoName: string): string {
  const key = `${componentName}.demo.${demoName}`;
  const sourceCode = sourceCodeMap[key];
  
  if (!sourceCode) {
    console.warn(`Source code not found for: ${key}`);
    return `// Source code not found for ${key}`;
  }
  
  return sourceCode;
}

/**
 * Get all available source code keys
 */
export function getAvailableSourceCodeKeys(): string[] {
  return Object.keys(sourceCodeMap).sort();
}
