#!/usr/bin/env tsx
/**
 * Generates the machine-maintained half of the Agent Skills repo, and checks the
 * hand-written half for drift.
 *
 *   npm run skills:generate     write the generated reference files
 *   npm run skills:check        fail if they are stale, or a skill names a
 *                               symbol / icon the library does not export
 *
 * Each skill under `skills/skills/<name>/` has three parts:
 *
 *   SKILL.md              hand-written — workflow, decision tables, pitfalls
 *   references/api.md     hand-written — the curated narrative: how things
 *                         compose, which defaults matter, the union types
 *   references/props.md   GENERATED — exhaustive prop tables, straight from the
 *                         same extraction that feeds llms.txt
 *
 * The split is deliberate. Prop tables go stale silently and are the least
 * interesting part to write by hand, so they are generated. Everything that
 * required judgement stays hand-written and is instead *checked*: `--check`
 * re-parses every `import { … } from '@platform-blocks/…'` in every fenced code
 * block and every `<Icon name="…">`, and fails on anything the library no longer
 * provides. That is the failure this repo is actually exposed to — a skill that
 * confidently teaches an API which no longer exists.
 *
 * Inputs are the artifacts written by scripts/generate-demos.ts. Run
 * `npm run demos:generate` first.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join, resolve } from 'path';

const repoRoot = process.cwd();
const generatedDir = join(repoRoot, 'apps', 'platform-blocks.com', 'data', 'generated');
const uiSrc = join(repoRoot, 'packages', 'ui', 'src');
const chartsSrc = join(repoRoot, 'packages', 'charts', 'src');

/** The skills repo is a sibling checkout of the monorepo. */
const skillsRoot = resolve(
  process.env.PLATFORM_BLOCKS_SKILLS_DIR ?? join(repoRoot, '..', 'skills'),
);
const skillsDir = join(skillsRoot, 'skills');

const GENERATED_BANNER =
  '<!-- GENERATED by scripts/generate-skills.ts in platform-blocks/platform-blocks. Do not edit by hand. -->';

// ---------------------------------------------------------------------------
// Which components each skill owns.
//
// Editorial, not derived: a skill's scope is a teaching decision, and several
// components legitimately belong to more than one (Pagination is both a
// navigation control and the DataTable footer). Components listed here get a
// generated prop table in that skill; everything else is reachable through the
// llms.txt escape hatch each SKILL.md ends with.
// ---------------------------------------------------------------------------
const SKILL_COMPONENTS: Record<string, string[]> = {
  'platform-blocks-layout': [
    'Flex', 'Grid', 'Block', 'Card', 'Surface', 'AppShell', 'Space', 'Divider', 'Masonry',
  ],
  'platform-blocks-forms': [
    'Form', 'ControlField', 'Input', 'TextArea', 'NumberInput', 'Select', 'AutoComplete',
    'Checkbox', 'Radio', 'Switch', 'SegmentedControl', 'Slider', 'PinInput', 'PhoneInput',
    'ColorInput', 'FileInput', 'DatePickerInput', 'TimePickerInput', 'Search',
  ],
  'platform-blocks-feedback-overlays': [
    'Toast', 'Dialog', 'Popover', 'Menu', 'Tooltip', 'ContextMenu', 'Alert',
    'Overlay', 'LoadingOverlay', 'Loader', 'Progress', 'Ring', 'Skeleton',
  ],
  'platform-blocks-data-display': [
    'DataTable', 'Table', 'DataList', 'Tree', 'Timeline', 'Accordion', 'Collapse', 'Spoiler',
    'ListGroup', 'Badge', 'Chip', 'Avatar', 'Indicator', 'Rating', 'QRCode', 'Markdown',
  ],
  'platform-blocks-navigation': [
    'Tabs', 'Breadcrumbs', 'Pagination', 'Stepper', 'TableOfContents', 'Spotlight',
    'Link', 'MenuItemButton',
  ],
};

/** Skills that get the icon-registry reference (they show `<Icon name="…">`). */
const SKILLS_WITH_ICONS = [
  'platform-blocks-layout',
  'platform-blocks-forms',
  'platform-blocks-feedback-overlays',
  'platform-blocks-data-display',
  'platform-blocks-navigation',
];

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------
interface PropRecord {
  name: string;
  type?: string;
  required?: boolean;
  defaultValue?: string;
  description?: string;
}

function readJson<T>(file: string): T {
  const path = join(generatedDir, file);
  if (!existsSync(path)) {
    throw new Error(
      `Missing ${file}. Run \`npm run demos:generate\` before \`npm run skills:generate\`.`,
    );
  }
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

/** Every icon name registered in the default Tabler-backed registry. */
function readIconNames(): string[] {
  const file = join(uiSrc, 'components', 'Icon', 'icons', 'tabler.ts');
  const source = readFileSync(file, 'utf8');
  const names = new Set<string>();
  // Registry entries are `name: <svg path data>` at one indent level.
  for (const match of source.matchAll(/^\s{2}'?([A-Za-z][A-Za-z0-9-]*)'?\s*:/gm)) {
    names.add(match[1]);
  }
  return [...names].sort((a, b) => a.localeCompare(b));
}

/**
 * Public value exports of a package barrel.
 *
 * Deliberately source-level rather than an import of the built package: the
 * check has to run before a build, and `export * from './x'` is resolved one
 * level deep so re-exported barrels (Indicator, Toggle) are not missed.
 */
function readBarrelExports(entry: string, seen = new Set<string>()): Set<string> {
  const names = new Set<string>();
  if (!existsSync(entry) || seen.has(entry)) return names;
  seen.add(entry);

  let source = readFileSync(entry, 'utf8');
  source = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*/g, '');

  for (const match of source.matchAll(/export\s+(?:type\s+)?\{([^}]*)\}/g)) {
    for (const raw of match[1].split(',')) {
      const part = raw.trim();
      if (!part) continue;
      // `type Foo` / `Foo as Bar` — the exported name is what consumers import.
      const aliased = part.match(/\bas\s+([A-Za-z_$][\w$]*)$/);
      const name = aliased ? aliased[1] : part.replace(/^type\s+/, '').trim();
      if (name && name !== 'default') names.add(name);
    }
  }

  for (const match of source.matchAll(/export\s+(?:const|function|class)\s+([A-Za-z_$][\w$]*)/g)) {
    names.add(match[1]);
  }

  // Follow `export * from './x'` one level so barrel re-exports resolve.
  for (const match of source.matchAll(/export\s+\*\s+from\s+'([^']+)'/g)) {
    const rel = match[1];
    const base = resolve(dirname(entry), rel);
    for (const candidate of [`${base}.ts`, `${base}.tsx`, join(base, 'index.ts'), join(base, 'index.tsx')]) {
      if (existsSync(candidate)) {
        for (const name of readBarrelExports(candidate, seen)) names.add(name);
        break;
      }
    }
  }

  return names;
}

/** Subpath modules: `@platform-blocks/ui/Navigation` etc. */
function readSubpathExports(subpath: string): Set<string> {
  for (const candidate of [
    join(uiSrc, 'components', subpath, 'index.ts'),
    join(uiSrc, 'components', subpath, 'index.tsx'),
    join(uiSrc, subpath, 'index.ts'),
  ]) {
    if (existsSync(candidate)) return readBarrelExports(candidate);
  }
  return new Set();
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------
const escapeCell = (value: string) =>
  value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();

function propTable(props: PropRecord[]): string {
  const lines = [
    '| Prop | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const prop of props) {
    lines.push(
      `| \`${prop.name}\` | ${prop.type ? `\`${escapeCell(prop.type)}\`` : '—'} | ${
        prop.required ? 'yes' : '—'
      } | ${prop.defaultValue ? `\`${escapeCell(prop.defaultValue)}\`` : '—'} | ${
        escapeCell(prop.description ?? '')
      } |`,
    );
  }
  return lines.join('\n');
}

function buildPropsDoc(
  skill: string,
  components: string[],
  propsByComponent: Record<string, PropRecord[]>,
  metaByComponent: Record<string, { description?: string; category?: string }>,
  version: string,
): string {
  const out: string[] = [
    GENERATED_BANNER,
    '',
    `# ${skill} — generated prop reference`,
    '',
    'Exhaustive prop tables, extracted from the component sources of',
    `\`@platform-blocks/ui@${version}\` — the same data behind`,
    'https://platform-blocks.com/llms.txt.',
    '',
    'This file is generated. `api.md` next to it is hand-written and covers what',
    'these tables cannot: how the pieces compose, which defaults matter, and the',
    'gotchas. Read `api.md` first; come here for the complete surface of one prop.',
    '',
    `Components in this skill: ${components.map((c) => `\`${c}\``).join(', ')}.`,
    '',
  ];

  for (const component of components) {
    const props = propsByComponent[component];
    out.push(`## ${component}`, '');
    const description = metaByComponent[component]?.description;
    if (description) out.push(escapeCell(description), '');
    if (!props?.length) {
      out.push('_No extracted props — see the hand-written `api.md`._', '');
      continue;
    }
    out.push(propTable(props), '');
  }

  return `${out.join('\n').trimEnd()}\n`;
}

function buildIconsDoc(names: string[], version: string): string {
  const columns = 4;
  const rows: string[] = [];
  for (let i = 0; i < names.length; i += columns) {
    rows.push(`| ${names.slice(i, i + columns).map((n) => `\`${n}\``).join(' | ').padEnd(0)} |`);
  }
  // Pad the final row so the table stays rectangular.
  const remainder = names.length % columns;
  if (remainder) {
    rows[rows.length - 1] = rows[rows.length - 1].replace(/ \|$/, `${' |'.repeat(columns - remainder)}`);
  }

  return `${[
    GENERATED_BANNER,
    '',
    '# Icon registry — every built-in `name`',
    '',
    `\`@platform-blocks/ui@${version}\` registers ${names.length} icons by default,`,
    'backed by `@tabler/icons-react-native`. These are the only strings `name`',
    'accepts out of the box — anything else renders nothing, so **do not guess an',
    'icon name**; pick one from this list or pass a component instead.',
    '',
    '```tsx',
    "import { Icon, IconButton } from '@platform-blocks/ui';",
    '',
    '<Icon name="check" size="sm" />',
    '<IconButton icon="trash" onPress={remove} accessibilityLabel="Delete" />',
    '',
    '// Not in the registry? Pass any icon component or element instead:',
    "import { IconRocket } from '@tabler/icons-react-native';",
    '<IconButton icon={IconRocket} onPress={launch} accessibilityLabel="Launch" />',
    '```',
    '',
    'There is no public API for registering additional names —',
    '`registerIcon` / `registerIcons` exist in the source but are not exported',
    'from the package root or from `@platform-blocks/ui/Icon`. Pass a component',
    'for anything outside this list.',
    '',
    '## Names',
    '',
    `| | | | |`,
    `| --- | --- | --- | --- |`,
    ...rows,
    '',
  ].join('\n').trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// Drift checks over the hand-written files
// ---------------------------------------------------------------------------
interface Problem {
  file: string;
  line: number;
  message: string;
}

const CODE_BLOCK = /```(?:tsx|ts|jsx|js)\n([\s\S]*?)```/g;
const IMPORT_STATEMENT = /import\s+(?:type\s+)?\{([^}]*)\}\s*from\s*'(@platform-blocks\/[^']+)'/g;
/**
 * Icon-registry usages. `name=` alone is far too broad — `Form.Field`,
 * `Tabs.Screen` and `<meta>` all use it — so it is only read inside an `<Icon>`
 * tag. `icon` slots (IconButton, Alert, Spotlight actions) take registry names
 * wherever they take a string.
 */
const ICON_USAGES: RegExp[] = [
  /<Icon\b[^>]*?\bname=["']([A-Za-z][A-Za-z0-9-]*)["']/g,
  /\bicon=["']([A-Za-z][A-Za-z0-9-]*)["']/g,
  /\bicon:\s*'([A-Za-z][A-Za-z0-9-]*)'/g,
];

function lineOf(text: string, index: number): number {
  return text.slice(0, index).split('\n').length;
}

function checkFile(
  file: string,
  text: string,
  resolvers: {
    ui: Set<string>;
    charts: Set<string>;
    subpath: (name: string) => Set<string>;
    icons: Set<string>;
  },
): Problem[] {
  const problems: Problem[] = [];

  for (const block of text.matchAll(CODE_BLOCK)) {
    const code = block[1];
    const blockOffset = block.index! + block[0].indexOf(code);

    for (const statement of code.matchAll(IMPORT_STATEMENT)) {
      const source = statement[2];
      let valid: Set<string>;
      if (source === '@platform-blocks/ui') valid = resolvers.ui;
      else if (source === '@platform-blocks/charts') valid = resolvers.charts;
      else if (source.startsWith('@platform-blocks/ui/')) {
        valid = resolvers.subpath(source.slice('@platform-blocks/ui/'.length));
      } else continue;

      // An empty set means the subpath itself could not be resolved.
      if (valid.size === 0) {
        problems.push({
          file,
          line: lineOf(text, blockOffset + statement.index!),
          message: `import from '${source}' — no such module in packages/ui/src`,
        });
        continue;
      }

      const specifiers = statement[1].replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
      for (const raw of specifiers.split(',')) {
        const part = raw.trim();
        if (!part) continue;
        const name = part.replace(/^type\s+/, '').split(/\s+as\s+/)[0].trim();
        if (!name || valid.has(name)) continue;
        problems.push({
          file,
          line: lineOf(text, blockOffset + statement.index!),
          message: `'${name}' is not exported from '${source}'`,
        });
      }
    }

    for (const pattern of ICON_USAGES) {
      for (const usage of code.matchAll(pattern)) {
        const name = usage[1];
        if (resolvers.icons.has(name)) continue;
        problems.push({
          file,
          line: lineOf(text, blockOffset + usage.index!),
          message: `icon name "${name}" is not in the built-in registry`,
        });
      }
    }
  }

  return problems;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
function listSkillFiles(): string[] {
  const files: string[] = [];
  for (const skill of readdirSync(skillsDir, { withFileTypes: true })) {
    if (!skill.isDirectory()) continue;
    const skillPath = join(skillsDir, skill.name);
    files.push(join(skillPath, 'SKILL.md'));
    const references = join(skillPath, 'references');
    if (!existsSync(references)) continue;
    for (const reference of readdirSync(references)) {
      if (reference.endsWith('.md')) files.push(join(references, reference));
    }
  }
  return files.filter(existsSync);
}

function main() {
  const check = process.argv.includes('--check');

  if (!existsSync(skillsDir)) {
    const hint =
      `skills repo not found at ${skillsRoot}\n` +
      '   Clone https://github.com/platform-blocks/skills next to this repo, or set\n' +
      '   PLATFORM_BLOCKS_SKILLS_DIR to its path.';

    // `verify:packages` runs this on every release. A contributor who has not
    // cloned the (separate) skills repo should not be blocked from building the
    // library, so a missing checkout is a skip, not a failure. Being stale when
    // the checkout *is* present still fails.
    if (check) {
      console.warn(`⚠️  ${hint}\n   Skipping the skills check.`);
      return;
    }
    console.error(`❌ ${hint}`);
    process.exit(1);
  }

  const version = JSON.parse(
    readFileSync(join(repoRoot, 'packages', 'ui', 'package.json'), 'utf8'),
  ).version as string;

  const propsByComponent = readJson<Record<string, PropRecord[]>>('components-props.json');
  const metaByComponent = readJson<Record<string, { description?: string; category?: string }>>(
    'components-meta.json',
  );
  const iconNames = readIconNames();

  // --- generated files -----------------------------------------------------
  const outputs = new Map<string, string>();

  for (const [skill, components] of Object.entries(SKILL_COMPONENTS)) {
    if (!existsSync(join(skillsDir, skill))) {
      console.warn(`⚠️  skill "${skill}" is not in the skills repo — skipping`);
      continue;
    }
    const missing = components.filter((c) => !(c in propsByComponent));
    if (missing.length) {
      console.warn(`⚠️  ${skill}: no extracted props for ${missing.join(', ')}`);
    }
    outputs.set(
      join(skillsDir, skill, 'references', 'props.md'),
      buildPropsDoc(skill, components, propsByComponent, metaByComponent, version),
    );
  }

  const iconsDoc = buildIconsDoc(iconNames, version);
  for (const skill of SKILLS_WITH_ICONS) {
    if (!existsSync(join(skillsDir, skill))) continue;
    outputs.set(join(skillsDir, skill, 'references', 'icons.md'), iconsDoc);
  }

  const stale: string[] = [];
  for (const [path, content] of outputs) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === content) continue;
    stale.push(path);
    if (!check) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content, 'utf8');
    }
  }

  // --- drift checks --------------------------------------------------------
  const resolvers = {
    ui: readBarrelExports(join(uiSrc, 'index.ts')),
    charts: readBarrelExports(join(chartsSrc, 'index.ts')),
    subpath: (name: string) => readSubpathExports(name),
    icons: new Set(iconNames),
  };

  const problems: Problem[] = [];
  for (const file of listSkillFiles()) {
    problems.push(...checkFile(file, readFileSync(file, 'utf8'), resolvers));
  }

  // Advisory: components the library exports but the docs pipeline skips. Each
  // skill's escape hatch points agents at /llms/components/<Name>.md, so a
  // missing page is a dead end. Not fatal — this is a docs gap, not a skills bug.
  const undocumented = Object.keys(SKILL_COMPONENTS)
    .flatMap((skill) => SKILL_COMPONENTS[skill])
    .filter((component) => !(component in metaByComponent));
  if (undocumented.length) {
    console.warn(
      `⚠️  no docs page for ${[...new Set(undocumented)].join(', ')} — ` +
        'the llms.txt escape hatch cannot reach them',
    );
  }

  // --- report --------------------------------------------------------------
  const rel = (path: string) => path.slice(skillsRoot.length + 1);

  if (problems.length) {
    console.error(`❌ ${problems.length} stale reference${problems.length === 1 ? '' : 's'} in the skills repo:`);
    for (const problem of problems) {
      console.error(`   ${rel(problem.file)}:${problem.line} — ${problem.message}`);
    }
  }

  if (check) {
    if (stale.length) {
      console.error(
        `❌ ${stale.length} generated file${stale.length === 1 ? ' is' : 's are'} stale — run \`npm run skills:generate\` and commit the result:`,
      );
      for (const path of stale) console.error(`   ${rel(path)}`);
    }
    if (stale.length || problems.length) process.exit(1);
    console.log(
      `✅ skills are in sync (${outputs.size} generated files, ${resolvers.ui.size} ui exports, ${iconNames.length} icons)`,
    );
    return;
  }

  console.log(
    stale.length
      ? `✅ wrote ${stale.length} generated file${stale.length === 1 ? '' : 's'} to ${rel(skillsDir)}`
      : `✅ generated files already up to date (${outputs.size} checked)`,
  );
  if (problems.length) {
    console.error('   Fix the stale references above — `--check` treats them as failures.');
    process.exit(1);
  }
}

main();
