import type { BrandName } from './icons';

/** How each brand writes its own name, for button titles, alt text and lists. */
export const brandLabels: Record<BrandName, string> = {
  google: 'Google',
  'google-play': 'Google Play',
  'galaxy-store': 'Galaxy Store',
  facebook: 'Facebook',
  discord: 'Discord',
  android: 'Android',
  apple: 'Apple',
  'apple-podcasts': 'Apple Podcasts',
  'app-store': 'App Store',
  'app-gallery': 'AppGallery',
  anthropic: 'Anthropic',
  openai: 'OpenAI',
  chrome: 'Chrome',
  spotify: 'Spotify',
  github: 'GitHub',
  x: 'X',
  microsoft: 'Microsoft',
  linkedin: 'LinkedIn',
  slack: 'Slack',
  youtube: 'YouTube',
  'youtube-music': 'YouTube Music',
  mastercard: 'Mastercard',
  visa: 'Visa',
  threads: 'Threads',
  bluesky: 'Bluesky',
  pinterest: 'Pinterest',
  snapchat: 'Snapchat',
  wechat: 'WeChat',
  reddit: 'Reddit',
  amazon: 'Amazon',
  'amazon-music': 'Amazon Music',
  twitch: 'Twitch',
  tiktok: 'TikTok',
  expo: 'Expo',
  react: 'React',
  nodejs: 'Node.js',
  npm: 'npm',
  stripe: 'Stripe',
  'apple-pay': 'Apple Pay',
  'google-pay': 'Google Pay',
  paypal: 'PayPal',
  'apple-music': 'Apple Music',
  soundcloud: 'SoundCloud',
  whatsapp: 'WhatsApp',
  telegram: 'Telegram',
  signal: 'Signal',
  meta: 'Meta',
  discover: 'Discover',
  amex: 'American Express',
  messenger: 'Messenger',
  instagram: 'Instagram',
  zoom: 'Zoom',
  typescript: 'TypeScript',
  css: 'CSS',
};
